# Generated by Django 5.2.11 on 2026-03-20 20:46

import django.contrib.postgres.fields
import django.db.models.deletion
import netbox.models.deletion
import netbox_dhcp_kea_plugin.models
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("extras", "0134_owner"),
        ("ipam", "0086_gfk_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DHCPHARelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("mode", models.CharField(default="hot-standby", max_length=20)),
                ("heartbeat_delay", models.PositiveIntegerField(default=10000)),
                ("max_response_delay", models.PositiveIntegerField(default=60000)),
                ("max_ack_delay", models.PositiveIntegerField(default=5000)),
                ("max_unacked_clients", models.PositiveIntegerField(default=5)),
                ("max_rejected_lease_updates", models.PositiveIntegerField(default=10)),
                ("enable_multi_threading", models.BooleanField(default=True)),
                ("http_dedicated_listener", models.BooleanField(default=True)),
                ("http_listener_threads", models.PositiveIntegerField(default=4)),
                ("http_client_threads", models.PositiveIntegerField(default=4)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP HA Relationship",
                "verbose_name_plural": "DHCP HA Relationships",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DHCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="active", max_length=50)),
                ("ha_role", models.CharField(blank=True, max_length=20)),
                (
                    "ha_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ha_port",
                    models.PositiveIntegerField(blank=True, default=8080, null=True),
                ),
                ("ha_tls", models.BooleanField(default=False)),
                ("ha_auto_failover", models.BooleanField(default=True)),
                ("ha_basic_auth_user", models.CharField(blank=True, max_length=100)),
                (
                    "ha_basic_auth_password",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "ctrl_socket_type",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "ctrl_socket_http_address",
                    models.CharField(blank=True, default="127.0.0.1", max_length=255),
                ),
                (
                    "ctrl_socket_http_port",
                    models.PositiveIntegerField(blank=True, default=8000, null=True),
                ),
                (
                    "ctrl_socket_unix_path",
                    models.CharField(
                        blank=True,
                        default="/var/run/kea/kea-dhcp4-socket",
                        max_length=255,
                    ),
                ),
                (
                    "ha_relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servers",
                        to="netbox_dhcp_kea_plugin.dhcpharelationship",
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_servers",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dhcp_servers",
                        to="ipam.service",
                    ),
                ),
                (
                    "service_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_servers",
                        to="ipam.servicetemplate",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Server",
                "verbose_name_plural": "DHCP Servers",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Hook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("library_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_standard", models.BooleanField(default=False)),
                (
                    "allowed_processes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        size=None,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, null=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hook",
                "verbose_name_plural": "Hooks",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HookGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "library_path",
                    models.CharField(
                        blank=True, default="/usr/lib64/kea/hooks", max_length=255
                    ),
                ),
                (
                    "hooks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hook_groups",
                        to="netbox_dhcp_kea_plugin.hook",
                    ),
                ),
                (
                    "servers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hook_groups",
                        to="netbox_dhcp_kea_plugin.dhcpserver",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hook Group",
                "verbose_name_plural": "Hook Groups",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OptionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("distinctive_name", models.CharField(max_length=100, unique=True)),
                ("option_space", models.CharField(default="dhcp4", max_length=50)),
                ("delivery_type", models.CharField(default="standard", max_length=20)),
                ("data", models.TextField()),
                ("always_send", models.BooleanField(default=False)),
                ("csv_format", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Data",
                "verbose_name_plural": "Option Data",
                "ordering": (
                    "delivery_type",
                    "vendor_option_space",
                    "option_space",
                    "distinctive_name",
                ),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="option_data",
            field=models.ManyToManyField(
                blank=True,
                related_name="dhcp_servers",
                to="netbox_dhcp_kea_plugin.optiondata",
            ),
        ),
        migrations.CreateModel(
            name="ClientClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("test_expression", models.TextField(blank=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("only_in_additional_list", models.BooleanField(default=False)),
                (
                    "next_server",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("server_hostname", models.CharField(blank=True, max_length=255)),
                ("boot_file_name", models.CharField(blank=True, max_length=255)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "servers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="client_classes",
                        to="netbox_dhcp_kea_plugin.dhcpserver",
                    ),
                ),
                (
                    "option_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="client_classes",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Class",
                "verbose_name_plural": "Client Classes",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OptionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.PositiveIntegerField()),
                ("option_type", models.CharField(default="string", max_length=20)),
                ("option_space", models.CharField(default="dhcp4", max_length=50)),
                ("is_array", models.BooleanField(default=False)),
                ("encapsulate", models.CharField(blank=True, max_length=100)),
                ("record_types", models.CharField(blank=True, max_length=500)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_standard", models.BooleanField(default=False)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Definition",
                "verbose_name_plural": "Option Definitions",
                "ordering": ("vendor_option_space", "code", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="optiondata",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="option_data_instances",
                to="netbox_dhcp_kea_plugin.optiondefinition",
            ),
        ),
        migrations.CreateModel(
            name="StorkAgentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("operating_mode", models.CharField(default="both", max_length=20)),
                ("agent_port", models.PositiveIntegerField(default=8080)),
                (
                    "prometheus_exporter_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "prometheus_exporter_port",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("prometheus_per_subnet_stats", models.BooleanField(default=True)),
                ("skip_tls_cert_verification", models.BooleanField(default=False)),
                ("log_level", models.CharField(default="INFO", max_length=10)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stork Agent Group",
                "verbose_name_plural": "Stork Agent Groups",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="stork_agent_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servers",
                to="netbox_dhcp_kea_plugin.storkagentgroup",
            ),
        ),
        migrations.CreateModel(
            name="StorkServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="active", max_length=50)),
                ("rest_port", models.PositiveIntegerField(default=8080)),
                (
                    "rest_base_url",
                    models.CharField(blank=True, default="/", max_length=255),
                ),
                ("use_tls", models.BooleanField(default=False)),
                ("db_host", models.CharField(default="localhost", max_length=255)),
                ("db_port", models.PositiveIntegerField(default=5432)),
                ("db_name", models.CharField(default="stork", max_length=100)),
                ("db_user", models.CharField(default="stork", max_length=100)),
                ("db_ssl_mode", models.CharField(default="disable", max_length=20)),
                ("enable_metrics", models.BooleanField(default=False)),
                ("grafana_url", models.URLField(blank=True)),
                (
                    "default_agent_registration",
                    models.CharField(default="agent-token", max_length=20),
                ),
                (
                    "stork_version",
                    models.CharField(blank=True, default="stable", max_length=20),
                ),
                ("log_level", models.CharField(default="INFO", max_length=10)),
                (
                    "ip_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stork_servers",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stork Server",
                "verbose_name_plural": "Stork Servers",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="storkagentgroup",
            name="stork_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_groups",
                to="netbox_dhcp_kea_plugin.storkserver",
            ),
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                (
                    "valid_lifetime",
                    models.PositiveIntegerField(
                        default=netbox_dhcp_kea_plugin.models.get_default_valid_lifetime
                    ),
                ),
                (
                    "max_lifetime",
                    models.PositiveIntegerField(
                        default=netbox_dhcp_kea_plugin.models.get_default_max_lifetime
                    ),
                ),
                ("routers_option_offset", models.PositiveIntegerField(default=1)),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subnet_restrictions",
                        to="netbox_dhcp_kea_plugin.clientclass",
                    ),
                ),
                (
                    "evaluate_additional_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subnet_evaluations",
                        to="netbox_dhcp_kea_plugin.clientclass",
                    ),
                ),
                (
                    "option_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subnet_items",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
                (
                    "prefix",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dhcp_config",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subnet_items",
                        to="netbox_dhcp_kea_plugin.dhcpserver",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet",
                "verbose_name_plural": "Subnets",
                "ordering": ("prefix",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SubnetPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "client_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pool_restrictions",
                        to="netbox_dhcp_kea_plugin.clientclass",
                    ),
                ),
                (
                    "evaluate_additional_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pool_evaluations",
                        to="netbox_dhcp_kea_plugin.clientclass",
                    ),
                ),
                (
                    "ip_range",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dhcp_pool_config",
                        to="ipam.iprange",
                    ),
                ),
                (
                    "option_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pool_configs",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnet_pools",
                        to="netbox_dhcp_kea_plugin.subnet",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnet Pool",
                "verbose_name_plural": "Subnet Pools",
                "ordering": ("subnet", "ip_range"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VendorOptionSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("enterprise_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_option_spaces",
                        to="dcim.manufacturer",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Option Space",
                "verbose_name_plural": "Vendor Option Spaces",
                "ordering": ("enterprise_id", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="optiondefinition",
            name="vendor_option_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_definitions",
                to="netbox_dhcp_kea_plugin.vendoroptionspace",
            ),
        ),
        migrations.AddField(
            model_name="optiondata",
            name="vendor_option_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="option_data_instances",
                to="netbox_dhcp_kea_plugin.vendoroptionspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="dhcpserver",
            constraint=models.UniqueConstraint(
                fields=("ip_address", "service_template"),
                name="unique_ip_address_service_template",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="optiondefinition",
            unique_together={("vendor_option_space", "code")},
        ),
    ]
