# Generated by Django 5.2.10 on 2026-01-28 19:51

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dcim", "0225_gfk_indexes"),
        ("extras", "0134_owner"),
        ("ipam", "0086_gfk_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DHCPHARelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("mode", models.CharField(default="hot-standby", max_length=20)),
                ("heartbeat_delay", models.PositiveIntegerField(default=10000)),
                ("max_response_delay", models.PositiveIntegerField(default=60000)),
                ("max_ack_delay", models.PositiveIntegerField(default=5000)),
                ("max_unacked_clients", models.PositiveIntegerField(default=5)),
                ("max_rejected_lease_updates", models.PositiveIntegerField(default=10)),
                ("enable_multi_threading", models.BooleanField(default=True)),
                ("http_dedicated_listener", models.BooleanField(default=True)),
                ("http_listener_threads", models.PositiveIntegerField(default=4)),
                ("http_client_threads", models.PositiveIntegerField(default=4)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP HA Relationship",
                "verbose_name_plural": "DHCP HA Relationships",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OptionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("distinctive_name", models.CharField(max_length=100, unique=True)),
                ("option_space", models.CharField(default="dhcp4", max_length=50)),
                ("delivery_type", models.CharField(default="standard", max_length=20)),
                ("data", models.TextField()),
                ("always_send", models.BooleanField(default=False)),
                ("csv_format", models.BooleanField(default=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Data",
                "verbose_name_plural": "Option Data",
                "ordering": (
                    "delivery_type",
                    "vendor_option_space",
                    "option_space",
                    "distinctive_name",
                ),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DHCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("ha_role", models.CharField(blank=True, max_length=20)),
                ("ha_url", models.URLField(blank=True)),
                ("ha_auto_failover", models.BooleanField(default=True)),
                ("ha_basic_auth_user", models.CharField(blank=True, max_length=100)),
                (
                    "ha_basic_auth_password",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "ha_relationship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servers",
                        to="netbox_dhcp_kea_plugin.dhcpharelationship",
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_servers",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dhcp_servers",
                        to="ipam.service",
                    ),
                ),
                (
                    "service_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_servers",
                        to="ipam.servicetemplate",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "option_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dhcp_servers",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Server",
                "verbose_name_plural": "DHCP Servers",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ClientClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("test_expression", models.TextField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("local_definitions", models.BooleanField(default=False)),
                (
                    "next_server",
                    models.GenericIPAddressField(
                        blank=True, null=True, protocol="IPv4"
                    ),
                ),
                ("server_hostname", models.CharField(blank=True, max_length=255)),
                ("boot_file_name", models.CharField(blank=True, max_length=255)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "servers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="client_classes",
                        to="netbox_dhcp_kea_plugin.dhcpserver",
                    ),
                ),
                (
                    "option_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="client_classes",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Class",
                "verbose_name_plural": "Client Classes",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OptionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.PositiveIntegerField()),
                ("option_type", models.CharField(default="string", max_length=20)),
                ("option_space", models.CharField(default="dhcp4", max_length=50)),
                ("is_array", models.BooleanField(default=False)),
                ("encapsulate", models.CharField(blank=True, max_length=100)),
                ("record_types", models.CharField(blank=True, max_length=500)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_standard", models.BooleanField(default=False)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Option Definition",
                "verbose_name_plural": "Option Definitions",
                "ordering": ("vendor_option_space", "code", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="optiondata",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="option_data_instances",
                to="netbox_dhcp_kea_plugin.optiondefinition",
            ),
        ),
        migrations.CreateModel(
            name="PrefixDHCPConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("valid_lifetime", models.PositiveIntegerField(default=3600)),
                ("max_lifetime", models.PositiveIntegerField(default=7200)),
                ("routers_option_offset", models.PositiveIntegerField(default=1)),
                (
                    "client_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="prefix_configs",
                        to="netbox_dhcp_kea_plugin.clientclass",
                    ),
                ),
                (
                    "option_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="prefix_configs",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
                (
                    "prefix",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dhcp_config",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prefix_configs",
                        to="netbox_dhcp_kea_plugin.dhcpserver",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "DHCP Prefix",
                "verbose_name_plural": "DHCP Prefixes",
                "ordering": ("prefix",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VendorOptionSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("enterprise_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_option_spaces",
                        to="dcim.manufacturer",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Option Space",
                "verbose_name_plural": "Vendor Option Spaces",
                "ordering": ("enterprise_id", "name"),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name="optiondefinition",
            name="vendor_option_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_definitions",
                to="netbox_dhcp_kea_plugin.vendoroptionspace",
            ),
        ),
        migrations.AddField(
            model_name="optiondata",
            name="vendor_option_space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="option_data_instances",
                to="netbox_dhcp_kea_plugin.vendoroptionspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="dhcpserver",
            constraint=models.UniqueConstraint(
                fields=("ip_address", "service_template"),
                name="unique_ip_address_service_template",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="optiondefinition",
            unique_together={("vendor_option_space", "code")},
        ),
    ]
