# Generated by Django 5.2.12 on 2026-03-30 17:09

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0134_owner"),
        ("netbox_dhcp_kea_plugin", "0003_reservation_mode_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionDataIPSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("ordinal", models.PositiveSmallIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "ipam"), ("model", "ipaddress")),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "option_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_sources",
                        to="netbox_dhcp_kea_plugin.optiondata",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
                ),
            ],
            options={
                "verbose_name": "IP Source",
                "verbose_name_plural": "IP Sources",
                "ordering": ("ordinal",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="optiondata",
            name="data",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Option value/data (leave empty when using IP sources)",
            ),
        ),
    ]
