# Generated by Django 6.0.6 on 2026-06-08 22:12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    # Pin to stable, long-standing core migrations rather than whatever was
    # latest when this was generated. makemigrations pins the newest core
    # migration of each referenced app; on a dev checkout that is ahead of the
    # released NetBox, those pins point at migrations a released install does
    # not have (NodeNotFoundError). MACAddress was introduced in dcim 0199
    # (NetBox 4.2); the ipam/extras pins match 0006_ddns. These exist across the
    # supported NetBox range, so the migration stays portable.
    dependencies = [
        ("dcim", "0199_macaddress"),
        ("extras", "0134_owner"),
        ("ipam", "0086_gfk_indexes"),
        ("netbox_dhcp_kea_plugin", "0006_ddns"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnet",
            name="auto_reservations",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="StaticReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_static_reservation",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "mac_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_static_reservations",
                        to="dcim.macaddress",
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_reservations",
                        to="netbox_dhcp_kea_plugin.subnet",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Reservation",
                "verbose_name_plural": "Static Reservations",
                "ordering": ("subnet", "ip_address"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subnet", "mac_address"),
                        name="unique_subnet_mac_reservation",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
