# Generated by Django 6.0.6 on 2026-06-08 22:12

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0237_module_remove_local_context_data"),
        ("extras", "0139_alter_customfieldchoiceset_extra_choices"),
        ("ipam", "0090_vlangroup_recompute_total_vlan_ids"),
        ("netbox_dhcp_kea_plugin", "0006_ddns"),
    ]

    operations = [
        migrations.AddField(
            model_name="subnet",
            name="auto_reservations",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="StaticReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_static_reservation",
                        to="ipam.ipaddress",
                    ),
                ),
                (
                    "mac_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dhcp_static_reservations",
                        to="dcim.macaddress",
                    ),
                ),
                (
                    "subnet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_reservations",
                        to="netbox_dhcp_kea_plugin.subnet",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Reservation",
                "verbose_name_plural": "Static Reservations",
                "ordering": ("subnet", "ip_address"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subnet", "mac_address"),
                        name="unique_subnet_mac_reservation",
                    )
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
