# Generated by Django 6.0.7 on 2026-08-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp_kea_plugin", "0007_subnet_auto_reservations_staticreservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpserver",
            name="ctrl_socket_proxy_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ha_egress_base_port",
            field=models.PositiveIntegerField(blank=True, default=18080, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="ha_proxy_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
