# Generated by Django 6.0.7 on 2026-08-20 07:21

from django.db import migrations, models


def move_credentials_to_relationship(apps, schema_editor):
    """Lift each relationship's HA credentials off its member servers.

    The primary is the authority: it is where the rest of the HA configuration
    is already resolved from. Only if the primary has none do we fall back to
    any member that does, so a cluster whose credentials were set on the standby
    alone does not silently lose them.
    """
    DHCPHARelationship = apps.get_model("netbox_dhcp_kea_plugin", "DHCPHARelationship")

    for relationship in DHCPHARelationship.objects.all():
        members = relationship.servers.order_by("name")
        source = members.filter(ha_role="primary").first()
        if source is None or not source.ha_basic_auth_user:
            source = members.exclude(ha_basic_auth_user="").first()
        if source is None:
            continue

        relationship.ha_basic_auth_user = source.ha_basic_auth_user
        relationship.ha_basic_auth_password = source.ha_basic_auth_password
        relationship.save(update_fields=["ha_basic_auth_user", "ha_basic_auth_password"])


def push_credentials_back_to_servers(apps, schema_editor):
    """Reverse: write the shared pair onto every member.

    Every member gets the same values, which is the symmetric configuration the
    forward migration exists to produce — not necessarily the asymmetric one that
    was there before.
    """
    DHCPHARelationship = apps.get_model("netbox_dhcp_kea_plugin", "DHCPHARelationship")

    for relationship in DHCPHARelationship.objects.all():
        relationship.servers.update(
            ha_basic_auth_user=relationship.ha_basic_auth_user,
            ha_basic_auth_password=relationship.ha_basic_auth_password,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_dhcp_kea_plugin",
            "0008_dhcpserver_ctrl_socket_proxy_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpharelationship",
            name="ha_basic_auth_user",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dhcpharelationship",
            name="ha_basic_auth_password",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(
            move_credentials_to_relationship,
            push_credentials_back_to_servers,
        ),
        migrations.RemoveField(
            model_name="dhcpserver",
            name="ha_basic_auth_user",
        ),
        migrations.RemoveField(
            model_name="dhcpserver",
            name="ha_basic_auth_password",
        ),
    ]
