# Generated by Django 6.0.7 on 2026-08-20 10:12

from django.db import migrations, models


def move_proxy_flag_to_relationship(apps, schema_editor):
    """Enable the proxy on any relationship that had it on at least one member.

    A mixed cluster never worked in either direction, so any member with the
    flag set is taken as the intent for the whole relationship rather than
    trying to pick a majority.
    """
    DHCPHARelationship = apps.get_model("netbox_dhcp_kea_plugin", "DHCPHARelationship")

    for relationship in DHCPHARelationship.objects.all():
        if relationship.servers.filter(ha_proxy_enabled=True).exists():
            relationship.ha_proxy_enabled = True
            relationship.save(update_fields=["ha_proxy_enabled"])


def push_proxy_flag_back_to_servers(apps, schema_editor):
    """Reverse: every member takes the relationship's value."""
    DHCPHARelationship = apps.get_model("netbox_dhcp_kea_plugin", "DHCPHARelationship")

    for relationship in DHCPHARelationship.objects.all():
        relationship.servers.update(ha_proxy_enabled=relationship.ha_proxy_enabled)


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp_kea_plugin", "0009_ha_basic_auth_on_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcpharelationship",
            name="ha_proxy_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            move_proxy_flag_to_relationship,
            push_proxy_flag_back_to_servers,
        ),
        migrations.RemoveField(
            model_name="dhcpserver",
            name="ha_proxy_enabled",
        ),
    ]
