# Generated by Django 6.0.7 on 2026-08-28 14:55

from django.db import migrations, models


def preserve_current_endpoint(apps, schema_editor):
    """Pick the endpoint each server already resolves to, so nothing moves.

    url() used to prefer ip_address.dns_name and fall back to the address. A
    server with a DNS name therefore keeps rendering that name, and one without
    keeps rendering its address — the upgrade changes no URL, it only makes the
    choice explicit and editable.
    """
    StorkServer = apps.get_model("netbox_dhcp_kea_plugin", "StorkServer")

    for server in StorkServer.objects.select_related("ip_address"):
        dns_name = ((server.ip_address.dns_name if server.ip_address_id else "") or "").strip().rstrip(".")
        if dns_name:
            server.endpoint_type = "dns"
            # Left unbound and blank on purpose: the fallback still resolves it,
            # and inventing a binding to a record nobody chose would then
            # protect and cascade-delete that record.
        else:
            server.endpoint_type = "ip"
        server.save(update_fields=["endpoint_type"])


def restore_default_endpoint(apps, schema_editor):
    """Reverse: the columns are about to be dropped."""
    StorkServer = apps.get_model("netbox_dhcp_kea_plugin", "StorkServer")
    StorkServer.objects.update(endpoint_type="dns", endpoint_record_id=None, endpoint_fqdn="")


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dhcp_kea_plugin", "0009_ha_relationship_settings_and_pki"),
    ]

    operations = [
        migrations.AddField(
            model_name="storkserver",
            name="endpoint_fqdn",
            field=models.CharField(blank=True, max_length=253),
        ),
        migrations.AddField(
            model_name="storkserver",
            name="endpoint_record_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storkserver",
            name="endpoint_type",
            field=models.CharField(default="dns", max_length=10),
        ),
        migrations.RunPython(preserve_current_endpoint, restore_default_endpoint),
    ]
