# Generated by Django 5.2.10 on 2026-02-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp_kea_plugin", "0010_subnet_client_class_rename_evaluate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subnet",
            name="option_data",
            field=models.ManyToManyField(
                blank=True,
                related_name="subnet_items",
                to="netbox_dhcp_kea_plugin.optiondata",
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subnet_items",
                to="netbox_dhcp_kea_plugin.dhcpserver",
            ),
        ),
    ]
