# Generated by Django 6.0.7 on 2026-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp_kea_plugin", "0010_storkserver_endpoint_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclass",
            name="template_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="user_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="decline_probation_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="user_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
