# Generated by Django 6.0.7 on 2026-09-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp_kea_plugin", "0011_user_context_and_decline_probation"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclass",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientclass",
            name="valid_lifetime",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="max_valid_lifetime",
            field=models.PositiveIntegerField(default=7200),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dhcpserver",
            name="valid_lifetime",
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name="subnet",
            name="rebind_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subnet",
            name="renew_timer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
