# Generated by Django 5.2.11 on 2026-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_dhcp_kea_plugin", "0020_dhcpserver_ctrl_socket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storkserver",
            name="db_user",
            field=models.CharField(default="stork", max_length=100),
        ),
    ]
